services:
  samba:
    image: dperson/samba:${VERSION:-latest}
    container_name: samba
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      - TZ=${TZ:?UTC}

      # advertise shares, default: true, or false (open ports 137, 138)
      # - NMBD=true

      # add a single user. If you need more, use command instead of environment
      # required arg: "<username>;<passwd>"
      # <username> for user
      # <password> for user
      # [ID] for user, default: ""
      # [group] for user, default: ""
      # - USER=user;user

      # set the UID for the samba share, default: ""
      - USERID=${PUID:-1000}

      # set the GID for the samba share, default: ""
      - GROUPID=${PGID:-1000}

      # add a single share. If you need more, use command instead of environment
      # required arg: "<name>;</path>"
      # <share_name>;
      # <path_to_share>;
      # [browsable] default:'yes' or 'no';
      # [read_only] default:'yes' or 'no';
      # [guest]: default: 'yes' or 'no';
      # [users]: default: 'all' or list of allowed users;
      # [admins] default: 'none' or list of admin users;
      # [writelist] default: 'none' or list of users that can write to read-only share;
      # [comment] default: 'none' or description of share
      # - SHARE=shared;/shared;yes;no;no;user;'none';'none';Homeserver

      # workgroup/domain name for share default: "MYGROUP"
      # - WORKGROUP=Homeserver

      # if set, disables recycle bin for shares
      # - RECYCLE=

      # if set, disables SMB2 minimum version
      # SMB: ""

    command: >
      -w "WORKGROUP"
      -u "${SAMBA_USERNAME:?Missing variable SAMBA_USERNAME};${SAMBA_PASSWORD:?Missing variable SAMBA_PASSWORD}"      
      -s "private;/shares/private;yes;no;no;${SAMBA_USERNAME:?Missing variable SAMBA_USERNAME};${SAMBA_USERNAME:?Missing variable SAMBA_USERNAME};${SAMBA_USERNAME:?Missing variable SAMBA_USERNAME}"
      -s "public;/shares/public;yes;no;no;all;${SAMBA_USERNAME:?Missing variable SAMBA_USERNAME};${SAMBA_USERNAME:?Missing variable SAMBA_USERNAME}"
      -p
    ports:
      - "137:137/udp" # required to advertise shares (NMBD)
      - "138:138/udp" # required to advertise shares (NMBD)
      - "139:139/tcp" # default smb port
      - "445:445/tcp" # default smb port
    read_only: false
    tmpfs:
      - /tmp
    volumes: # :z allows share to be used by multiple containers
      - ${DIRECTORY:?Missing variable DIRECTORY}/samba/config:/etc/samba
      - ${DIRECTORY:?Missing variable DIRECTORY}/samba/shares/private:/shares/private:z 
      - ${DIRECTORY:?Missing variable DIRECTORY}/samba/shares/public:/shares/public:z 
    labels:
      - homepage.group=Utilities
      - homepage.name=Samba
      - homepage.icon=mdi-folder-account
      - homepage.description=Opening windows to a wider world