services:
  samba:
    image: dockurr/samba:4.23.5@sha256:1f0de2ded42bded18d8c5f7b2e9f40521b5d7ddc7cf903ea54a0239cc4984a4e
    container_name: samba
    restart: unless-stopped
    environment:
      - USER=${USERNAME:?Missing variable USERNAME}
      - PASS=${PASSWORD:?Missing variable PASSWORD}
      - NAME=${SHARE_NAME:?Missing variable SHARE_NAME}
      - UID=${UID:-1000}
      - GID=${GID:-1000}
    ports:
      - "445:445"
    volumes:
      - ${DIRECTORY:?Missing variable DIRECTORY}/samba/config:/etc/samba
      - ${SHARE_PATH:?Missing variable SHARE_PATH}:/storage:z
    labels:
      - homepage.instance.internal.group=Services
      - homepage.instance.internal.name=Samba
      - homepage.instance.internal.icon=mdi-folder-account
      - homepage.instance.internal.description=Opening windows to a wider world
