networks:
  monitoring:
    name: monitoring
    driver: bridge

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

services:

  # https://grafana.com/docs/grafana/latest/
  grafana:
    image: grafana/grafana-oss:${GRAFANA_VERSION:-latest}
    container_name: grafana
    restart: unless-stopped
    ports:
      - ${GRAFANA_WEB_PORT:-3000}:3000
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.tls.certresolver=myresolver
      - traefik.http.services.grafana.loadbalancer.server.port=3000
      - homepage.group=Utilities
      - homepage.name=Grafana
      - homepage.icon=grafana.png
      - homepage.href=${HOST_URL:-http://localhost}:${GRAFANA_WEB_PORT:-3000}
      - homepage.description=Visualize your data, optimize your performance
      - homepage.widget.type=grafana
      - homepage.widget.url=${HOST_URL:-http://localhost}:${GRAFANA_WEB_PORT:-3000}
      - homepage.widget.username=${GRAFANA_USERNAME}
      - homepage.widget.password=${GRAFANA_PASSWORD}

  # https://prometheus.io/
  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION:-latest}
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ${PROMETHEUS_LOCATION:?Missing variable PROMETHEUS_LOCATION}/config:/etc/prometheus
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=365d' # DEFAULT : 15d
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - ${PROMETHEUS_WEB_PORT:-9090}:9090
    expose:
      - 9090
    networks:
      - monitoring
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - traefik.enable=true
      - traefik.http.routers.prometheus.tls.certresolver=myresolver
      - traefik.http.services.prometheus.loadbalancer.server.port=9090
      - homepage.group=Utilities
      - homepage.name=Prometheus
      - homepage.icon=prometheus.png
      - homepage.href=${HOST_URL:-http://localhost}:${PROMETHEUS_WEB_PORT:-9090}
      - homepage.description=From metrics to insight
      - homepage.widget.type=prometheus
      - homepage.widget.url=${HOST_URL:-http://localhost}:${PROMETHEUS_WEB_PORT:-9090}

  # https://grafana.com/docs/loki/latest/
  loki:
    image: grafana/loki:${LOKI_VERSION:-latest}
    container_name: loki
    restart: unless-stopped
    ports:
      - ${LOKI_WEB_PORT:-3100}:3100
    volumes:
      - ${LOKI_LOCATION:?Missing variable LOKI_LOCATION}/config:/etc/config
      - ${LOKI_LOCATION:?Missing variable LOKI_LOCATION}/data:/loki
    expose:
      - 3100
    networks:
      - monitoring
    command: -config.file=/etc/config/loki.yml
  
  # https://grafana.com/docs/loki/latest/send-data/promtail/
  promtail:
    image: grafana/promtail:${PROMTAIL_VERSION:-latest}
    container_name: promtail
    restart: unless-stopped
    ports:
      - ${PROMTAIL_WEB_PORT:-9080}:9080
    volumes:
      - ${PROMTAIL_LOCATION:?Missing variable PROMTAIL_LOCATION}/config:/etc/config
      - ${PROMTAIL_LOCATION:?Missing variable LOKI_LOCATION}/data:/promtail
      - ${LOGS_LOCATION:?Missing variable LOGS_LOCATION}:/var/log:ro
    expose:
      - 9080
    networks:
      - monitoring
    command: -config.file=/etc/config/promtail.yml

  ### EXPORTERS

  # https://github.com/prometheus/node_exporter
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - monitoring
 
  # https://github.com/google/cadvisor
  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    expose:
      - 8080
    networks:
      - monitoring
  
  # https://docs.miguelndecarvalho.pt/projects/speedtest-exporter/
  speedtest-exporter:
    image: miguelndecarvalho/speedtest-exporter
    container_name: speedtest-exporter
    restart: unless-stopped
    # environment:
    #   - SPEEDTEST_PORT=<speedtest-port> #optional
    #   - SPEEDTEST_SERVER=<server-id> #optional
    # ports:
    #   - 90xx:9798
    expose:
      - 9798
    networks:
      - monitoring