version: '3'

services:
  vaultwarden:
    image: vaultwarden/server:${VERSION:-latest}
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      - ADMIN_TOKEN=${ADMIN_TOKEN:?Missing variable ADMIN_TOKEN}
      - SIGNUPS_ALLOWED=${SIGNUPS_ALLOWED:?Missing variable SIGNUPS_ALLOWED}
      - SMTP_HOST=${SMTP_HOST:?Missing variable SMTP_HOST}
      - SMTP_FROM=${SMTP_FROM:?Missing variable SMTP_FROM}
      - SMTP_PORT=${SMTP_PORT:?Missing variable SMTP_PORT}
      - SMTP_SECURITY=${SMTP_SECURITY:?Missing variable SMTP_SECURITY}
      - SMTP_USERNAME=${SMTP_USERNAME:?Missing variable SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD:?Missing variable SMTP_PASSWORD}
      - DOMAIN=${DOMAIN:?Missing variable DOMAIN}
    volumes:
      - ${DIRECTORY:?Missing variable DIRECTORY}/vaultwarden/data/:/data/
    ports:
      - ${WEB_PORT:-80}:80
    labels:
      - homepage.group=Utilities
      - homepage.name=Vaultwarden
      - homepage.icon=vaultwarden.png
      - homepage.href="${HOST_URL:-http://localhost}:${WEB_PORT:-80}"
      - homepage.description=Community driven password manager