services:
  excalidraw:
    container_name: excalidraw
    image: excalidraw/excalidraw:${VERSION:-latest}
    restart: unless-stopped
    ports:
     - ${WEB_PORT:-80}:80
    labels:
      - traefik.enable=true
      - traefik.http.routers.excalidraw.tls.certresolver=myresolver
      - traefik.http.services.excalidraw.loadbalancer.server.port=80
      - homepage.group=Utilities
      - homepage.name=Excalidraw
      - homepage.icon=excalidraw.png
      - homepage.instance.public.href=https://excalidraw.${DOMAIN:?Missing variable DOMAIN}
      - homepage.instance.internal.href=${HOST_URL:-http://localhost}:${WEB_PORT:-80}
      - homepage.description=Virtual whiteboard for sketching hand-drawn like diagrams