services:
  home:
    image: ghcr.io/gethomepage/homepage:${VERSION:-latest}
    container_name: homepage
    restart: unless-stopped
    volumes:
      - ${DIRECTORY:?Missing variable DIRECTORY}/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
      # - /mnt/drive1:/mnt/drive1:ro # (optional) Other mounted drives for widget integrations
    ports:
      - "${WEB_PORT:-3000}:3000"
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage.tls.certresolver=myresolver
      - traefik.http.services.homepage.loadbalancer.server.port=3000
      - homepage.group=Utilities
      - homepage.name=Homepage
      - homepage.icon=homepage.png
      - homepage.href=${HOST_URL:-http://localhost}:${WEB_PORT:-3000}
      - homepage.description=Highly customizable homepage with Docker and service API integrations.
