version: "3.3"

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:${VERSION:-latest}
    container_name: homepage
    restart: unless-stopped
    volumes:
      - ${DIRECTORY:?Missing variable DIRECTORY}/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
    ports:
      - "${WEB_PORT:-3000}:3000"
    labels:
      - homepage.group=Utilities
      - homepage.name=Homepage
      - homepage.icon=homepage.png
      - homepage.href="${HOST_URL:-http://localhost}:${WEB_PORT:-3000}"
      - homepage.description=Highly customizable homepage with Docker and service API integrations.
