version: "3.4"

services:
  broker:
    image: docker.io/library/redis:7
    container_name: paperless-ngx-broker
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    image: docker.io/library/postgres:15
    container_name: paperless-ngx-db
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  paperless-ngx:
    image: ghcr.io/paperless-ngx/paperless-ngx:${VERSION:-latest}
    container_name: paperless-ngx
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - ${WEB_PORT:-8000}:8000
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ${PAPERLESS_LOCATION:?Missing variable PAPERLESS_LOCATION}/data:/usr/src/paperless/data
      - ${PAPERLESS_LOCATION:?Missing variable PAPERLESS_LOCATION}/media:/usr/src/paperless/media
      - ${PAPERLESS_LOCATION:?Missing variable PAPERLESS_LOCATION}/export:/usr/src/paperless/export
      - ${PAPERLESS_LOCATION:?Missing variable PAPERLESS_LOCATION}/consume:/usr/src/paperless/consume
    environment:
      - PAPERLESS_REDIS=redis://broker:6379
      - PAPERLESS_DBHOST=db
      # The UID and GID of the user used to run paperless in the container. Set this
      # to your UID and GID on the host so that you have write access to the
      # consumption directory.
      - USERMAP_UID=1000
      - USERMAP_GID=100
      - PAPERLESS_ADMIN_USER=${ADMIN_USER:?Missing variable ADMIN_USER}
      - PAPERLESS_ADMIN_PASSWORD=${ADMIN_PASSWORD:?Missing variable ADMIN_PASSWORD}
      
      # Additional languages to install for text recognition, separated by a
      # whitespace. Note that this is
      # different from PAPERLESS_OCR_LANGUAGE (default=eng), which defines the
      # language used for OCR.
      # The container installs English, German, Italian, Spanish and French by
      # default.
      # See https://packages.debian.org/search?keywords=tesseract-ocr-&searchon=names&suite=buster
      # for available languages.
      #PAPERLESS_OCR_LANGUAGES: tur ces

      # Adjust this key if you plan to make paperless available publicly. It should
      # be a very long sequence of random characters. You don't need to remember it.
      #PAPERLESS_SECRET_KEY: change-me

      # Use this variable to set a timezone for the Paperless Docker containers. If not specified, defaults to UTC.
      #PAPERLESS_TIME_ZONE: America/Los_Angeles

      # The default language to use for OCR. Set this to the language most of your
      # documents are written in.
      #PAPERLESS_OCR_LANGUAGE: eng
    labels:
      - homepage.group=Utilities
      - homepage.name=Paperless-ngx
      - homepage.icon=paperless-ngx.png
      - homepage.href=${HOST_URL:-http://localhost}:${WEB_PORT:-8000}
      - homepage.description=Scan, index and archive all your physical documents

volumes:
  pgdata:
  redisdata: