version: '3.5'

services:
  jellyfin:
    image: jellyfin/jellyfin:${VERSION:-latest}
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - ${WEB_PORT:-8096}:8096
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    environment:
      - JELLYFIN_PublishedServerUrl=${HOST_URL:-http://localhost} # Optional - alternative address used for autodiscovery
    volumes:
      - ${MEDIA_DIRECTORY:?Missing variable MEDIA_DIRECTORY}/jellyfin/config:/config
      - ${MEDIA_DIRECTORY:?Missing variable MEDIA_DIRECTORY}/jellyfin/cache:/cache
      - ${LIBRARY_DIRECTORY:?Missing variable LIBRARY_DIRECTORY}/movies:/movies
      - ${LIBRARY_DIRECTORY:?Missing variable LIBRARY_DIRECTORY}/videos:/videos
      - ${LIBRARY_DIRECTORY:?Missing variable LIBRARY_DIRECTORY}/series:/series
      - ${LIBRARY_DIRECTORY:?Missing variable LIBRARY_DIRECTORY}/music:/music
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.tls.certresolver=myresolver
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096
      - homepage.group=Media
      - homepage.name=Jellyfin
      - homepage.icon=jellyfin.png
      - homepage.href=${HOST_URL:-http://localhost}:${WEB_PORT:-8096}
      - homepage.description=The Free Software Media System