services:
  uptime-kuma:
    image: louislam/uptime-kuma:1.23.15
    container_name: uptime-kuma
    restart: unless-stopped
    volumes:
      - ${DIRECTORY:?Missing variable DIRECTORY}/uptime-kuma:/app/data
      # - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - ${WEB_PORT:-3001}:3001
    labels: 
      - traefik.enable=true
      - traefik.http.routers.uptime-kuma.tls.certresolver=myresolver
      - traefik.http.services.uptime-kuma.loadbalancer.server.port=3001
      - homepage.group=Monitoring
      - homepage.name=Uptime-kuma
      - homepage.instance.public.href=https://uptime-kuma.${DOMAIN:?Missing variable DOMAIN}
      - homepage.instance.internal.href=${HOST_URL:-http://localhost}:${WEB_PORT:-3001}
      - homepage.icon=uptime-kuma.png
      - homepage.description=A fancy self-hosted monitoring tool 