services:
  # https://docs.miguelndecarvalho.pt/projects/speedtest-exporter/
  speedtest-exporter:
    image: miguelndecarvalho/speedtest-exporter:v3.5.4@sha256:f1064d49124c7fc45faabb87c6c876a2fd04e92b3dc14d4b871301217ba30fed
    container_name: speedtest-exporter
    restart: unless-stopped
    ports:
      - 9798:9798
  
  # https://github.com/AthennaMind/opnsense-exporter
  opnsense-exporter:
    image: ghcr.io/athennamind/opnsense-exporter:0.0.17@sha256:04a28ad984a091ea1e8371cf515da8b38b1d00416f53e6b5c9d68fec39d92ce0
    container_name: opensense-exporter
    restart: unless-stopped
    command:
      - --web.listen-address=:8080
    environment:
      OPNSENSE_EXPORTER_OPS_PROTOCOL: "${OPNSENSE_PROTOCOL:-https}"
      OPNSENSE_EXPORTER_OPS_INSECURE: "${OPNSENSE_INSECURE:-false}"
      OPNSENSE_EXPORTER_OPS_API: "${OPNSENSE_ADDRESS:?Missing variable OPNSENSE_ADDRESS}"
      OPNSENSE_EXPORTER_INSTANCE_LABEL: "${OPNSENSE_INSTANCE_LABEL:?Missing variable OPNSENSE_INSTANCE_LABEL}"
      OPNSENSE_EXPORTER_OPS_API_KEY: "${OPNSENSE_API_KEY:?Missing variable OPNSENSE_API_KEY}"
      OPNSENSE_EXPORTER_OPS_API_SECRET: "${OPNSENSE_API_SECRET:?Missing variable OPNSENSE_API_SECRET}"
    ports:
      - 8080:8080